### ISSUE TITLE
Problem with initialization of ADLX

### ISSUE THREAD

**Issue by Szdunek** [Rem0o/FanControl.ADLX#1]
I had issue with controlling fan on my GPU.  Downloaded compiled ADLX from AppVeyor (as of 12 Feb) but encountered error below. Tried to recompile from source on my own with success but FanControl throws exact same error (just different project paths)

* OS: Windows 10 x64
* CPU: Ryzen 7 1700X @ 3.8 Ghz (OC)
* Ram: 4x 8GB DDR4 3000Mhz GoodRam IRDM
* GPU: AsRock RX6750XT 12GB PhantomGaming (Latest drivers - 22.11.2)
* MB: Asus B450-Plus Tuf Gaming (v1.0)
* Data was collected on FanControl V145 but after update to V146 its still same situation

![Screenshot_1](https://user-images.githubusercontent.com/56074822/218283068-b881571d-70b0-40eb-bdd7-961c3b51b7de.png)
![Screenshot_2](https://user-images.githubusercontent.com/56074822/218283071-e872c2f0-949f-48b4-993b-d80adc021ca0.png)
![Screenshot_3](https://user-images.githubusercontent.com/56074822/218283125-2456a7ea-b500-4236-8eeb-892647189e34.png)

Unblocked every file one by one but still throws same errors

log.txt content (sorry for .net set to Polish but I bet you can still understand):

Nie można załadować pliku lub zestawu - means: Could not load file or project 'ADLXWrapper, ....

```
11.02.2023 22:55:33: Unhandled exception in FanControl v1.0.0.0
11.02.2023 22:55:33: System.IO.FileNotFoundException: Nie można załadować pliku lub zestawu 'ADLXWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' lub jednej z jego zależności. Nie można odnaleźć określonego pliku.
Nazwa pliku: 'ADLXWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   w FanControl.ADLX.ADLXPlugin.Close()
   w System.Collections.Generic.List`1.ForEach(Action`1 action)
   w FanControl.Domain.ComputerAccessLayer.Close()
   w Autofac.Core.Disposer.Dispose(Boolean disposing)
   w Autofac.Util.Disposable.Dispose()
   w Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   w Autofac.Util.Disposable.Dispose()
   w Autofac.Core.Container.Dispose(Boolean disposing)
   w Autofac.Util.Disposable.Dispose()
   w FanControl.App.OnExit(ExitEventArgs e)
   w System.Windows.Application.DoShutdown()
   w System.Windows.Application.ShutdownImpl()
   w System.Windows.Application.ShutdownCallback(Object arg)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestawów jest wyłączone.
Aby włączyć rejestrowanie błędów powiązań zestawów, ustaw wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) równą 1.
Uwaga: z włączeniem rejestrowania błędów powiązań zestawów wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].

11.02.2023 22:55:50: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   w ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   w FanControl.ADLX.ADLXPlugin.Initialize() w C:\projects\fancontrol-adlx\ADLXPlugin.cs:wiersz 56
11.02.2023 22:55:51: ADLXWrapper.ADLXEception: Result: ADLX_FAIL 
Couldn't initialize ADLX
   w ADLXWrapper.Extensions.ThrowIfError(ADLX_RESULT result, String message)
   w FanControl.ADLX.ADLXPlugin.Initialize() w C:\projects\fancontrol-adlx\ADLXPlugin.cs:wiersz 56
11.02.2023 22:55:51: ADLX could not initialize or has no sensors.
```

**Comment by Rem0o** [comment]
I think the problem lies in the fact the the plugin dll is loaded onto the main appdomain, and its companion dlls are expected to be found in FanControl root folder, not the plugin folder.

**Comment by Szdunek** [comment]
I've put them in root folder too but still same error

![image](https://user-images.githubusercontent.com/56074822/218538923-895553ff-4baf-438f-b123-bb848ef2fc42.png)

**Comment by Szdunek** [comment]
Maybe I should disable GPU sensor from configuration and leave only ADLX, CPU and Motherboard sensors on? Will try when I get home from work and give you a feedback.

**Comment by Rem0o** [comment]
Your latest log shows adlx couldn’t initialize.  I’m not sure your system even supports ADLX in the first place.

**Comment by Szdunek** [comment]
I have AMD 6000 refresh GPU manufactured in 2022 (6750XT), windows 10 x64 and there is no info about other requirements in the internet. What should I do then to control my GPU fan using FanControl. FanControl detects gpu fan rpms properly - when I start any program/game that forces my GPU over 60* and fan starts. Maybe AMD software is blocking fan steering by any other app.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/218763983-579b720f-5075-4c30-8c78-888e3c97c00b.png)

**Comment by Szdunek** [comment]
AMD Adrenalin shows that there is 22.11.2 version currently installed on my system.

![image](https://user-images.githubusercontent.com/56074822/218783740-0e4f8cdf-3502-4259-8521-9627d6e94dec.png)

**Comment by Rem0o** [comment]
From what I can see, only the 7XXX series has the newer adrenaline, hence ADLX compatibility.

**Comment by Szdunek** [comment]
Sooooo there is no chances for me to control that damn fan trough FanControl untill lazy AMD releases new version of driver for 6XXX series? :<

**Comment by Rem0o** [comment]
Pretty much.

**Comment by Szdunek** [comment]
Okay will do that, thanks for your time.
