### ISSUE TITLE
Installation instructions are difficult to understand

### ISSUE THREAD

**Issue by Blarnix** [Rem0o/FanControl.ADLX#10]
Hi, so I had a bit of a more difficult time installing the plugin since the README confused me a bit with the wording making me think that _all_ of the dll's in the folder needed to be copied instead of the one. Doing this made FanControl repeatedly crash on startup, so it took me a while to figure out. My rambling aside, I think the wording in the installation should be more specific as to specify only copying the needed dll to the Plugins folder, since people like me with ADHD so easily miss that detail, haha. 
Thanks, and keep up the great work.

**Comment by ddenev** [comment]
@Blarnix, what are the correct dlls to copy?

**Comment by Blarnix** [comment]
> @Blarnix, what are the correct dlls to copy?

@ddenev Should just be ALDXWrapper.dll, but I couldn't get the sensors to connect correctly personally, so I haven't played with it since. I believe that is the correct one, though.

**Comment by ConvexTlc97** [comment]
Still unkown how to install this pluggin?

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
