### ISSUE TITLE
Plugin not showing up in Fan Control. 

### ISSUE THREAD

**Issue by SirSuperDeath** [Rem0o/FanControl.ADLX#11]
Amd software 23.5.3
I got the dll's from the dll folder in this repo and moved them into the plugins folder then restarted/closed the program.
plugin doesnt get detected by the software

![QIGDsbElL6](https://github.com/Rem0o/FanControl.ADLX/assets/6559285/5fe4b999-37c2-4595-be0b-00c07ac32f8b)
![explorer_j77E1yBdt1](https://github.com/Rem0o/FanControl.ADLX/assets/6559285/cab8775e-8e51-4c29-81f0-5aa8aa0b5b82)

also thanks for making this plugin/program <3

**Comment by Rem0o** [comment]
You don't need the FanControl.Plugins.dll inthere, only the ADLX ones. Also, any log.txt?

**Comment by SirSuperDeath** [comment]
> You don't need the FanControl.Plugins.dll inthere, only the ADLX ones. Also, any log.txt?

Nope I cant see a log.txt file in `D:\Useful programs\FanControl_net_4_8` if that is where it should show up. 
I also removed FanControl.plugins.dll from in the plugins folder and it still doesnt say the plugin is active.

**Comment by Rem0o** [comment]
Do you have the ADLX driver? RDNA3+ cards

**Comment by SirSuperDeath** [comment]
> Do you have the ADLX driver? RDNA3+ cards

ADLX Driver? (didnt know that was a thing) and I dont have a RDNA 3 GPU I have a RDNA2 GPU 
[https://www.techpowerup.com/gpu-specs/asrock-rx-6800-phantom-gaming-d-oc.b8342](url)

**Comment by Antrophyy** [comment]
@Rem0o So, I have a RDNA3 card (Saphire 7900 XTX) and just noticed that the plugin is not loading up for me either, though it did use to work just fine a couple days ago. I tried to replace the .dlls as well just to make sure but it is still not being loaded. 

I have the latest drivers 23.5.2. And the latest FanControl version (160). The log is not showing any errors at all. 

I updated the FanControl, so perhaps the latest fancontrol version broke something and now it's not recognizing your addon?

**Comment by Rem0o** [comment]
> I updated the FanControl, so perhaps the latest fancontrol version broke something and now it's not recognizing your addon?

Every other plugin still works, nothing changed on.

Any of you guys actually have the FanControl.ADLX.dll file in there? Just noticed @SirSuperDeath  doesn't have it in his screenshot.

**Comment by vmzd** [comment]
I think your appveyor artifact expired and got deleted, so no way to get that file without compiling

**Comment by PawOrmstrupMadsen** [comment]
i had this in my plugins folder, you can try to use it if you want to - until Rem0o rebuilds or re-uploads a new set of DLL's
[FanControl.ADLX.zip](https://github.com/Rem0o/FanControl.ADLX/files/12022012/FanControl.ADLX.zip)

**Comment by juanrugge** [comment]
> i had this in my plugins folder, you can try to use it if you want to - until Rem0o rebuilds or re-uploads a new set of DLL's [FanControl.ADLX.zip](https://github.com/Rem0o/FanControl.ADLX/files/12022012/FanControl.ADLX.zip)
> 
> on my machine it has stopped working, might be the new AMD drivers i updated.

thank you so much. couldn't solve this problem in any way, and using your plugins did the trick

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
