### ISSUE TITLE
Can't get the plugin to load (RDNA 3 user)

### ISSUE THREAD

**Issue by Neutraliz** [Rem0o/FanControl.ADLX#12]
Hi, 

First, thanks for the amazing work. 

I'm running a 7900XTX. Latest driver, lastest build of FanControl. 
Hwinfo plugin is working without issues, but I can't get ADLX to work. Maybe I'm missing something obvious ? I don't really know. 

![chrome_SDMoDkPctF](https://github.com/Rem0o/FanControl.ADLX/assets/138837278/4fa4c58d-a8ed-4049-8f29-56e415ba8352)
![HI6V82t0oe](https://github.com/Rem0o/FanControl.ADLX/assets/138837278/a9e2ed08-b766-49a1-917c-199bfe72f7ca)

Thanks in advance.

**Comment by MacIntoc** [comment]
I guess you need "FanControl.ADLX.dll".

By the way, you may remove "*.pdb" and "FanControl.Plugins.*".

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
