### ISSUE TITLE
Initialization failed after install the plugin

### ISSUE THREAD

**Issue by Rexadev** [Rem0o/FanControl.ADLX#14]
No controls and graphs shows but when I close the program it asks to save the config

**Comment by Rem0o** [comment]
What plugin? And what exactly is the problem? The fact the plugin doesn't initialize? The fact it ask for a save after you made some changes?

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
