### ISSUE TITLE
Download via appveyor of binaries is not working

### ISSUE THREAD

**Issue by zotabee** [Rem0o/FanControl.ADLX#15]
Hello,

https://ci.appveyor.com/project/Rem0o/fancontrol-adlx

`Build started
git clone -q --branch=main https://github.com/Rem0o/FanControl.ADLX.git C:\projects\fancontrol-adlx
git checkout -qf ee0ff5c0b7e4dc7a5[2](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L2)ff244669a7e0fc0d4ae20c
dotnet restore
  Determining projects to restore...
  Restored C:\projects\fancontrol-adlx\FanControl.ADLX.csproj (in 165 ms).
msbuild "C:\projects\fancontrol-adlx\FanControl.ADLX.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 16.11.2+f[3](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L3)22596[4](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L4)2 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
  FanControl.ADLX -> C:\projects\fancontrol-adlx\bin\Release\net48\FanControl.ADLX.dll
Discovering tests...OK
Collecting artifacts...
Found artifact 'bin\Release' matching 'Bin\Release' path
Uploading artifacts...
[1/1] bin\Release.zip ([7](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L7)7,4[8](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L8)7 bytes)...[10](https://ci.appveyor.com/project/Rem0o/fancontrol-adlx#L10)0%
Build success`

All I can see is a console but no download buttons nor any automatic download.

What supposed to happen over there ?

Thanks!

**Comment by midoriiro** [comment]
Nothing you can do, the git repository owner need to rebuild the release since all artifacts are deleted after one month.

Can you publish last release in proper section please ? @Rem0o

**Comment by zotabee** [comment]
@midoriiro Thank you for the information ! I guess I will wait for @Rem0o to find a solution.

**Comment by dayblox** [comment]
I would love to give this a try! Please trigger a build @Rem0o ♥

**Comment by Rem0o** [comment]
@dayblox  done

**Comment by midoriiro** [comment]
@Rem0o thanks for triggering the build. Any reason why this release is not automated, or at least release artifact is not provided easily like your other repository?

I could give it a look, even if this plug-in is an experimental one. It could be useful to many people to experiment with their AMD GPU and FanControl. What do you think?

**Comment by Rem0o** [comment]
@midoriiro 

Because until this project goes forward, I do not feel comfortable having regular users use this.  CPU consumption is way too high, there are leaks, and so on.

**Comment by julllleee** [comment]
@Rem0o could you please redo it as i would love to try this out ♥

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
