### ISSUE TITLE
FanControl will crash if refresh sensor detection with the ADLX plugins installed

### ISSUE THREAD

**Issue by Nelson0213** [Rem0o/FanControl.ADLX#16]
I have a gigabyte rx 6800. In stock condition FanControl can detect the gpu fan speed but can't control it. With the ADLX plugins installed the gpu fan can be controlled but the program will crash if refresh sensor detection.

**Comment by GameXtreme** [comment]
I need help with this too but mine is a Sapphire Pulse Radeon RX 6800. It will also crash when you wake up the computer from sleep mode. Is there a way this can be fixed without giving away my private key on my crypto wallet?

**Comment by Nelson0213** [comment]
Now I use the Radeon Software to control my gpu fan curve, not quite as good as FanControl but it's adequate

**Comment by GameXtreme** [comment]
I decided to use it too. I am glad that FanControl can still see the GPU fan speed control from Radeon Software so it can be mixed controlled with other motherboard/3rd party pump/fan controls.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
