### ISSUE TITLE
FanControl failing start

### ISSUE THREAD

**Issue by asuSlash** [Rem0o/FanControl.ADLX#17]
After installation of FanControl.ADLX plugin, my FanControl don't run. 
I downloaded FanControl.ADLX-main.zip and copy&paste all its files into FanControl's main folder, 
then 
i downloaded Release.zip by AppVeyor and copy&paste all its files into FanControl's Plugin folder.
Did i something wrong or forgot something?
Thanks for support me

**Comment by Rem0o** [comment]
does it starts properly without the plugin?

**Comment by asuSlash** [comment]
Yes, i use it since 4/5 months and works properly. 
Now, after installed ADLX plugin, don't start. It runs in background for few seconds and then close it self

**Comment by asuSlash** [comment]
Maybe I have found something, I have done many tests with each plugin's file and by deleting FanControl.ADLX.dll the software works correctly again.
I created a video to show step by step everything I did since a new installation of FanControl, to check if I made any mistakes or if there is a problem with the file I show.
https://youtu.be/Zp0ycZ1XmcU
I hope this helps to solve 🙏🏻

**Comment by DaedalusWren** [comment]
I followed your video step by step and had exactly the same issues. Never even had any instance of a GPU temperature. My GPU is an RX 580.

**Comment by asuSlash** [comment]
Hi @DaedalusWren, i recorded that video to explain my problem and make sure i did all rigth.
I'm waiting any advice from the owner @Rem0o to solve this common issue in AMD gpu users

**Comment by Rem0o** [comment]
Give https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1 a try

**Comment by asuSlash** [comment]
Thanks for answer, now it seems work properly on my RX 5500 XT, thank you so much!!!
