### ISSUE TITLE
Control mostly not possible, RPM only read once

### ISSUE THREAD

**Issue by oliverrahner** [Rem0o/FanControl.ADLX#2]
Most of the time, the fans do not react to setting a speed.
Sometimes, they do, though, but only for a short time (0.5 - 5 sec).
It feels like something else is overriding the setting, possibly the AMD Software itself...

Also, the fan speeds seem to be only updated when FanControl is starting up. At that time, the value is accurate, but it is never updated.

I have a Saphire Nitro+ RX 6800 XT, running on Win 11.
"AMD Software: Adrenalin Edition" version is 23.2.1

**Comment by Rem0o** [comment]
What are your fan settings looking like in Adrenalin? (Screenshot)

**Comment by oliverrahner** [comment]
I tried several different settings.
Most notably this:
![image](https://user-images.githubusercontent.com/2277681/220407624-c30f5024-b782-471e-9890-a5f56d4787bf.png)

And that:
![image](https://user-images.githubusercontent.com/2277681/220407641-89792bd8-930e-489e-a2d4-320646f2df5e.png)

**Comment by oliverrahner** [comment]
I created a unit test with only ADLXWrapper as a dependency.
This code only ever returns 0:

```csharp
[Fact]
public void ReadFanSpeed()
{
    var wrapper = new ADLXWrapper.ADLXWrapper();
    var system = wrapper.GetSystemServices();
    var gpus = system.GetGPUs();
    var perf = system.GetPerformanceMonitor();
    var metrics = gpus.Select(perf.GetGPUMetrics).ToArray();
    while (true)
    {
        _testOutputHelper.WriteLine(metrics[0].GetFanSpeed().ToString());
        Thread.Sleep(1000);
    }

}
```

**Comment by Rem0o** [comment]
Stupid question, but from Adrenalin, it reads 0, so is your fan spinning?

**Comment by oliverrahner** [comment]
Err... good point 😅
But: even when it's not 0, what I see with the above script is the same behavior as in FanControl:
It always shows the correct value first, and then repeats it on and on, no matter what the real value is.

**Comment by Rem0o** [comment]
Have you tried getting a new metrics everytime? Don't forget to dispose it after using it.

**Comment by oliverrahner** [comment]
Did that just now, it works!
I coded it the same way your plugin works.

So this way is ok:
```csharp
while (true)
{
    var metrics = gpus.Select(perf.GetGPUMetrics).ToArray();
    _testOutputHelper.WriteLine(metrics[0].GetFanSpeed().ToString());
    Thread.Sleep(1000);
}
```

**Comment by Rem0o** [comment]
I don't have a card myself, so all of this is pure guessing 😅

Now there are two possibilities.  1 => need to get a new ptr everytime you get a fan speed value, or as you did in your test, you need a new metrics object everytime and this one only has 1 set of value in time.

**Comment by oliverrahner** [comment]
I'm not exactly sure what you mean...
Like this?

```csharp
GPUMetrics metrics = null;
while (true)
{
    metrics = perf.GetGPUMetrics(mygpu);
    _testOutputHelper.WriteLine(metrics.GetFanSpeed().ToString());
    Thread.Sleep(1000);
}
```

**Comment by Rem0o** [comment]
> I'm just preparing a PR for the Plugin

The whole structure of the sensors will need to be reworked since they assumed of only needing 1 metrics object ever.

**Comment by oliverrahner** [comment]
![FanControl_8hsYcDd2CF](https://user-images.githubusercontent.com/2277681/220434230-78432839-1ca6-4288-85a3-5eb67a2ed588.gif)
So far so good :) PR incoming

**Comment by Rem0o** [comment]
Updated the fan sensor and temperature sensors.

**Comment by Rem0o** [comment]
Just saw your PR @oliverrahner, nice of you, but there was quite a lot more to do to make it work properly. Creating a new metrics object per sensor isn't ideal, since it can be shared between the temperature sensors too.

**Comment by oliverrahner** [comment]
Ah, got you :) Nevermind, hope it did help though

**Comment by oliverrahner** [comment]
I will test tomorrow! I'll probably not manage anymore testing today

**Comment by oliverrahner** [comment]
![image](https://user-images.githubusercontent.com/2277681/220463054-d94a59ae-c98c-4ac1-b10a-a24662509e3e.png)

Something went wrong... This pops up right after the start

**Comment by oliverrahner** [comment]
![image](https://user-images.githubusercontent.com/2277681/220463220-985890a0-93f5-4a84-a630-0711bae3261f.png)

**Comment by Rem0o** [comment]
logs?

**Comment by oliverrahner** [comment]
I found two:
- ADLXFanSensor.cs:26 [_metrics.Current might be null]
- ADLXPlugin.cs:37  [_metricsProviders might be null]

**Comment by oliverrahner** [comment]
After 57bb4c9, the situation is now:
- current RPM is read reliably
- control still shows the same behavior as before: sometimes the settings has no effect, and if it does, it only lasts some seconds before reverting back to the "standard"

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/220490242-fc58d4dd-a016-402f-b9d9-9c4fc13bb9ab.png)

This is the part that the plugin tries to control.  If you got it open with the graph visible, can you see the points move up and down with Fancontrol's command? Or do they revert back by themself?

**Comment by oliverrahner** [comment]
When Advanced Control is enabled (so I can see the graph you mentioned), fan control by Fan Control _never_ seems to work.
Even when I set a curve and modify it at will, the picture doesn't change.

I, again, tried to build an MWE for this, setting speed + 10% every 2 seconds and outputting the current speed one second later.

This pretty much sums it up:
![image](https://user-images.githubusercontent.com/2277681/220560297-1016488d-a440-45e0-b78d-b7b7b2886637.png)

In the middle, it worked, but before and after, it didn't... no change to AMD software in the meantime.

**Comment by oliverrahner** [comment]
This was the previous iteration:

```
Setting Fan Speed to 10%
Current Speed is 0
Current Temperature is 52

Setting Fan Speed to 20%
Current Speed is 0
Current Temperature is 52

Setting Fan Speed to 30%
Current Speed is 0
Current Temperature is 52

Setting Fan Speed to 40%
Current Speed is 0
Current Temperature is 52

Setting Fan Speed to 50%
Current Speed is 0
Current Temperature is 53

Setting Fan Speed to 60%
Current Speed is 0
Current Temperature is 53

Setting Fan Speed to 70%
Current Speed is 0
Current Temperature is 53

Setting Fan Speed to 80%
Current Speed is 0
Current Temperature is 54

Setting Fan Speed to 90%
Current Speed is 0
Current Temperature is 54

Setting Fan Speed to 100%
Current Speed is 0
Current Temperature is 54
```

**Comment by Rem0o** [comment]
@oliverrahner  when it stops working, what is the state looking like in adrenaline? Does it reverts to something?

**Comment by oliverrahner** [comment]
No visible changes... sometimes the graph changes to a constant (horizontal line), but only if I refresh it somehow, e.g. by switching off and on the "Advanced Control". This seemed very unreliable.

Funny enough, even after I closed FanControl, sometimes the fan would turn up to 100% and then go back after a few seconds. When I reset the settings in Adrenaline, this stops. But there is no indication to be found that something is currently overriding Adrenaline's settings.

Btw, FanControl still crashes frequently, both at startup and during regular operation. There are no log entries.

**Comment by oliverrahner** [comment]
While debugging the Plugin, I caught this exception during application exit:

![image](https://user-images.githubusercontent.com/2277681/220649462-7bd51b1a-2a91-4125-afd2-f68cb87f35a6.png)

**Comment by oliverrahner** [comment]
Found the culprit... I hadn't noticed before that your code explicitly enables Zero RPM. So, even if I had "manual control" on, the settings would only get into effect when the Zero RPM zone was left. That explains the weird behavior.
If I now start Fan Control and **then ** disable Zero RPM from inside Adrenaline, everything works as expected, including immediate update of the graph inside Adrenaline.

All settings below 15% seem to be completely ignored by Adrenaline. So when I go from 100% directly to 0% (with steps of 50%), the fans will be set to 50%, because 0% will be ignored.

https://user-images.githubusercontent.com/2277681/220655091-ea1b0bc2-ae13-4dfe-8fa4-0f0ce0df66c6.mp4

**Comment by Rem0o** [comment]
The zero RPM thing is odd.   The plugin turns it on, as I want to be able to turn off the fan from FanControl by hitting 0%.  You are basically saying that if it's on, nothing responds, and if it's turned off, every works as expected?

BTW the driver does have a function to give us the available speed range. In your case it's probably limited to 15-100.

**Comment by oliverrahner** [comment]
Nothing responds _as long a the temperature is below the Zero RPM threshold_. That's why I saw this seemingly weird behavior.
When the Zero RPM setting is changed via the API, that doesn't seem to be visible in Adrenaline.
I will try that with a script again and let you now how that works.

I guess what could be a good rule would be:
Turn on Zero RPM only if target speed is 0% (or <= low threshold).
Otherwise, turn Zero RPM off so target speed will go into effect no matter the current temperature.

**Comment by Rem0o** [comment]
Doing a similar thing with newer Nvidia cards, makes sense  it works in a similar fashion. 
Your above method should work. Still, there will be a "dead zone" in the control range, but I guess we'll have to live with it.  Otherwise we could valid speed range (15-100% in your case) to 1-100%, and set the 0 rpm mode at 0.  That would make it seamless.

**Comment by oliverrahner** [comment]
I had already seen the ADLXWrapper :) But I'm not yet willing to install the prerequisites to build it myself, I'm not into C++ at all...
BTW, I spent some minutes looking at the wrong documentation from AMD because I followed your link in README.md, which points to https://gpuopen.com/adl/, but should instead point to https://gpuopen.com/adlx/.
The current wrapper doesn't seem to expose this function: https://gpuopen.com/manuals/adlx/adlx-_d_o_x__i_a_d_l_x_manual_fan_tuning__get_fan_tuning_ranges/

Regarding visibility of the Zero RPM state in Adrenaline:
The setting *is* updated when the control curve changes (e.g. via `SetFanSpeed`), but not when _only_ the Zero RPM state changes.

I have decided to return my card in the next days and go for an Nvidia again instead 😅
So if you want some more tests done, I can only provide those for a very limited time range.

**Comment by Rem0o** [comment]
>  https://gpuopen.com/adl/, but should instead point to https://gpuopen.com/adlx/.

 *facepalm* 
 
 > The setting is updated when the control curve changes (e.g. via SetFanSpeed), but not when only the Zero RPM state changes.
 
 Good to know
 
 I will update the plugin with the changes I mentioned. If you got time sweet, otherwise, farewell to you onto the green team ;)

**Comment by oliverrahner** [comment]
Feedback on the current status:

I like that the setting now "snaps" to the lower limit.
- shouldn't that also happen on the upper limit? Even though I don't know if there are any cases out there where `Max != 100`
- even when target speed is set to 0 and the fans turn off, the target setting still snaps to `Min`. If find this non-intuitive. 
![image](https://user-images.githubusercontent.com/2277681/220958625-57cfc8a4-4a0a-4456-8dfc-fb5b64006ce3.png)
- aren't you missing to reset `_zeroRPMSet = false`?

I was thinking whether it would be good to enable Zero RPM also if `Min > val`, not only if `val == 0`. When the user (or the curve) sets `target_speed = 5`, but `Min == 15`, what does the user expect? Effective 0 (if possible) or effective 15?
On the pro side for the current behavior: the only situation where the fans behave "unpredictably" is `val == 0`. In all other cases, he can be sure what happens.
On the pro side for the alternative: the system will, in doubt, be quiter.

**Comment by Rem0o** [comment]
@oliverrahner  good stuff .

Last commit pretty much addressed everything you posted. 
* _zeroRPMSet  is now handled properly
* the val snapping with the minimum range will only happen if != 0. 
* I think I found why the dispose was firing an exception.   The helper needs to be "terminated" like it was "initialized" before disposing.

**Comment by oliverrahner** [comment]
Brilliant, the functions work perfect now!

Unfortunately, the crash is not gone.
On the bright side: The call stack looks different 😂

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ADLXWrapper.Bindings.ADLXPINVOKE.ADLXHelper_Terminate(HandleRef jarg1)
   at ADLXWrapper.Bindings.ADLXHelper.Terminate()
   at ADLXWrapper.ADLXWrapper.Dispose()
   at FanControl.ADLX.ADLXPlugin.Close() in D:\Coding\FanControl\FanControl.ADLX\ADLXPlugin.cs:line 43
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Close()
   at FanControl.Domain.ComputerAccessLayer.<>c.<Close>b__35_0(IBackendProvider x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FanControl.Domain.ComputerAccessLayer.Close()
   at FanControl.Domain.ComputerAccessLayer.Dispose()
   at Autofac.Core.Disposer.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at Autofac.Core.Container.Dispose(Boolean disposing)
   at Autofac.Util.Disposable.Dispose()
   at FanControl.App.OnExit(ExitEventArgs e)
   at System.Windows.Application.DoShutdown()
   at System.Windows.Application.ShutdownImpl()
   at System.Windows.Application.ShutdownCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FanControl.App.Main()
```

**Comment by Rem0o** [comment]
> On the bright side: The call stack looks different 😂

*Sigh*

I can't see exactly what I'm doing wrong. Maybe it's an order of thing. Right now the helper is disposed last, but maybe it needs to go first, I don't know :/

**Comment by oliverrahner** [comment]
Further finding:

Works:
```csharp
var adlxWrapper = new ADLXWrapper.ADLXWrapper();
var systemServices = adlxWrapper.GetSystemServices();
//var gpuTuningService = systemServices.GetGPUTuningService();
//var gpus = systemServices.GetGPUs();

//gpuTuningService?.Dispose();
//gpus?.ToList().ForEach(x => x.Dispose());
systemServices?.Dispose();
adlxWrapper?.Dispose();
```

Crashes with `ADLXWrapper.ADLXEception: Result: ADLX_ORPHAN_OBJECTS 
Couldn't terminate ADLX`:
```csharp
var adlxWrapper = new ADLXWrapper.ADLXWrapper();
var systemServices = adlxWrapper.GetSystemServices();
var gpuTuningService = systemServices.GetGPUTuningService();
//var gpus = systemServices.GetGPUs();

gpuTuningService?.Dispose();
//gpus?.ToList().ForEach(x => x.Dispose());
systemServices?.Dispose();
adlxWrapper?.Dispose();
```

Crashes with `System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`:
```csharp
var adlxWrapper = new ADLXWrapper.ADLXWrapper();
var systemServices = adlxWrapper.GetSystemServices();
var gpuTuningService = systemServices.GetGPUTuningService();
var gpus = systemServices.GetGPUs();

gpuTuningService?.Dispose();
gpus?.ToList().ForEach(x => x.Dispose());
systemServices?.Dispose();
adlxWrapper?.Dispose();
```

I am not able to dig deeper into this, as my knowledge of memory management is not very deep...

I'll now shutdown, switch cards and put this issue aside ;)

**Comment by Rem0o** [comment]
@oliverrahner  thanks a bunch!

**Comment by oliverrahner** [comment]
Thanks you for that great piece of software ;)

**Comment by Rem0o** [comment]
Update.  Found this sneaky one in a sample: 
https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/blob/b98ec6c3a1ba2ea31ff392f54c684788e7834ce8/Samples/csharp/DisplayEvents/DisplayEvents/mainDisplayEvents.cs#L56

They don't seem to call "acquire" first, but only release at the end.

 The release is responsible for the reference count internally, which explains the ADLX_ORPHAN_OBJECTS error we've seen.
 
 Updated the plugin with a "release" call for every IADLXInterface object at dispose time.

**Comment by XenHat** [comment]
> Found the culprit... I hadn't noticed before that your code explicitly enables Zero RPM. So, even if I had "manual control" on, the settings would only get into effect when the Zero RPM zone was left. That explains the weird behavior. If I now start Fan Control and **then ** disable Zero RPM from inside Adrenaline, everything works as expected, including immediate update of the graph inside Adrenaline.
> 
> All settings below 15% seem to be completely ignored by Adrenaline. So when I go from 100% directly to 0% (with steps of 50%), the fans will be set to 50%, because 0% will be ignored.
> FanControl_Ui0l11Dre7.mp4

I'm getting the same or similar behavior today on my 7900XTX.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/980408/32c0cbfb-ec2d-4ae3-a842-e554d144aec3)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/980408/0578d96d-dbcc-488d-959f-5dd990a5c0d0)

Controlling the GPU Fans only works if I manually disable **Zero RPM**, but disabling control of the fans from **Fan Control** automatically re-enables Zero RPM (which is desirable!).
The issue seems that it does not attempt to disable Zero RPM when enabling control of the fans, nor when doing fans speed adjustments.
Which behavior of the two would be preferable is up for debate, although I would prefer to see a toggle to enable Zero RPM in the expanded card, with the default being to disable Zero RPM **automatically**.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/980408/5df4ef17-7b57-4c1e-816a-c5c1e7daa901)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/980408/c7c471ba-686e-4a3f-90e9-84547c5eeea7)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/980408/40121e73-4b33-480d-9cea-432edb31c1c3)

Additional notes:
It would appear that on this specific GPU or SKU (PowerColor Radeon RX 7900XTX Red Devil Edition 24G), the fan is at 27%, any value set lower than this will result in the GPU fans stopping to spin entirely regardless of the Zero RPM setting.

I've made a video showcasing a few tests and behaviors:
https://youtu.be/e1dvrGassSE

**Comment by Rem0o** [comment]
For anyone here still active like @XenHat , I've made some changes and ditch the graph editing in favor of using the "target fan speed" slider equivalent in the API. This requires "Advanced Mode" to be off.  I haven't found the API to toggle that manually, or it's an implicit state, I don't know.

So for anywone that want to give it a shot, disable "Advanced Control" in Adrenalin, then start FanControl with the newer version of the plugin.  My hope is that it will take a lot less ressources to control the fan since modyfing the graph was equivalent to 6 api calls, 1 per point (5) + apply.

**Comment by Rem0o** [comment]
Good news:
https://github.com/Rem0o/FanControl.ADLX/discussions/36
