### ISSUE TITLE
Initalization failed

### ISSUE THREAD

**Issue by cornwolf** [Rem0o/FanControl.ADLX#20]
Hi all, 

I am getting an initialization failed when I try and add this plug-in. What am I missing or need to do, please?
![image](https://github.com/Rem0o/FanControl.ADLX/assets/20932874/df87e7ac-ee10-45ef-938b-d2ea09ef3ba4)

**Comment by Rem0o** [comment]
Any logs?

**Comment by gaspardleon** [comment]
in my experience you need to try restarting the program a number of times (can be 5 or 6 times)
Be sure to Discard configuration changes otherwise you'll need to roll that back to a backup as well

**Comment by Rem0o** [comment]
Give https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1 a try
