### ISSUE TITLE
ALDX incorrectly named the fan control for 7900XTX as Radeon Graphics?

### ISSUE THREAD

**Issue by CartierCodes** [Rem0o/FanControl.ADLX#21]
I added the FanControl.ADLX plugin. Here is what it detected.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/55055207/e29ef000-48dd-4f3c-bdec-3ba21c883f61)

At first, I was disappointed because it only had fan speed detected for my 7900XTX, no fan control. At some point while I was tinkering I accidentally set the AMD Integrated Graphics fan controller to 50%, and to my surprise, the speed sensor for the 7900XTX changed accordingly.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/55055207/75a6f903-f30f-40b3-9ed7-cfe55cd131ba)

Did the ADLX plugin sensors incorrectly name the fan controller as 'AMD Radeon(TM) Graphics' instead of 'AMD Radeon RX 7900 XTX', or is something really strange going on here?

**Comment by Rem0o** [comment]
If you look at the code here https://github.com/Rem0o/FanControl.ADLX/blob/main/ADLXPlugin.cs

it seems like the plugin is actually detecting 2 gpus. One is labaled as AMD Radeon (TM) and the other as the RX 7900.

**Comment by CartierCodes** [comment]
It makes sense that it detects 2 GPUs, since my the 7800x3d has integrated graphics. What I am confused about is why the fan controller doesn't correspond with the speed sensor of the same name (obviously I can rename it). It would make sense that only 1 controller would be present, since integrated graphics don't have a fan, but it doesn't make sense why the one controller it detects is labeled as AMD Radeon Graphics, when it in fact controls the RX 7900

**Comment by CartierCodes** [comment]
I tried refreshing the sensors and it actually crashed the program.
![image](https://github.com/Rem0o/FanControl.ADLX/assets/55055207/f1c5c0e4-543e-4a90-8663-7a8a0d59c223)

Upon reopening everything is still working. The AMD Radeon Graphics controller changes the fan speed of the 7900xtx

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
