### ISSUE TITLE
FanControl crashes after resuming from sleep mode

### ISSUE THREAD

**Issue by GameXtreme** [Rem0o/FanControl.ADLX#23]
Is this a ADLX plugin issue? Some say this plugin is causing the issue. I tried it without the ADLX plugin and I too can confirm, the program is still alive in the background after waking up from sleeping, controlling my 2023 Kraken AIO pump.

**Comment by StelimslimDEV** [comment]
@GameXtreme It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Support](https://exploreonsite.com/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by GameXtreme** [comment]
Hey StelimslimDEV,

why was your comment deleted?

**Comment by GameXtreme** [comment]
Hey StelimslimDEV,

why was your comment deleted?

**Comment by StelimslimDEV** [comment]
Yes mate and you don't have any reason to think negativity anad it's used to verify your authenticity.

**Comment by Rem0o** [comment]
Duplicate of https://github.com/Rem0o/FanControl.ADLX/issues/16
