### ISSUE TITLE
Fan Control still can't control the fan of my AMD GPU.

### ISSUE THREAD

**Issue by Tomajjs** [Rem0o/FanControl.ADLX#25]
![obrazek](https://github.com/Rem0o/FanControl.ADLX/assets/98232518/c0361b4b-89a3-4517-85b6-f7710716378b)
Even with force apply, the fan is still not controled by fancontrol.
I thought maybe GPU Tweak III was doing something with it, but the program is closed so it shouldn't do anything.
I have reinstalled FanControl because before it downloaded into system32 folder (no idea why) but mainly fancontrol would crash immediately. The plugin worked perfectly back then.
I have unblocked every single file of this plugin and the fancontrol.exe in the properties.
NO IDEA why the plugin does not work now
PLS HELP 🙏🙏🙏🙏
![obrazek](https://github.com/Rem0o/FanControl.ADLX/assets/98232518/55188574-f258-4cd9-8664-eea433c070ea)

**Comment by f4bio** [comment]
works for me... did you [unblock the DLLs](https://github.com/Rem0o/FanControl.ADLX/blob/main/README.md?plain=1#L21C88-L21C88)?

**Comment by Tomajjs** [comment]
> works for me... did you [unblock the DLLs](https://github.com/Rem0o/FanControl.ADLX/blob/main/README.md?plain=1#L21C88-L21C88)?

![obrazek](https://github.com/Rem0o/FanControl.ADLX/assets/98232518/4b0d2f2a-20db-4208-878d-4067dedf79f3)
I have unblocked every file in this screenshot plus fancontrol.exe .

And also, I have wrote this:
> I have unblocked every single file of this plugin and the fancontrol.exe in the properties.

**Comment by Rem0o** [comment]
What kind of settings do you got in Adrenaline?

**Comment by Tomajjs** [comment]
I don't know what exact settings do you want me to show you but I found some fan settings and I played with it a bit, I have even tried disabling it but does not help. Strange.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
