### ISSUE TITLE
Only increasing speed

### ISSUE THREAD

**Issue by SzymenL0K0** [Rem0o/FanControl.ADLX#27]
Hey.
I own an AMD rx 5700XT reddragon card. 
With this plugin I can half control the speed of the fans. 
I can increase the speed of the fans above how fast they spin normally. 
Unfortunately, I can't make them spin slower ( Like they spin at about 800RPM and i can increase it above for like 1600RPM but i cant get less than 800)

**Comment by Rem0o** [comment]
Thats normal, all cards have a limited minimum speed available from the driver api.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
