### ISSUE TITLE
Is it possible to only get AMD GPU Temperature sensors ?

### ISSUE THREAD

**Issue by code-guerilla** [Rem0o/FanControl.ADLX#28]
Is there a dll where i just be able to get the temperature sensors without control ? I am using AMD software to control the Fan of the GPU.

I know a bit of C# programming. But haven't used dll's so far. But simple instructions i can follow. 

Maybe it would be even handy. To make a amd just sensors fork. Or trying to implement that single piece in the main version. 

Help Appreciated :)

**Comment by Rem0o** [comment]
You can use the plugin and "not" use the control, by not toggling it on. If I remember correctly, the temperatures and RPM readings worked fine.
