### ISSUE TITLE
Plugin prevents fan control from starting

### ISSUE THREAD

**Issue by PaoloGB** [Rem0o/FanControl.ADLX#32]
First of all, thank you for the great work.

My setup:
Windows 11
Amd RX7800XT driver 23.20.44
Fan control 1.8.6
ADLX plugin latest release

After updating fan control to 1.8.6 the software would refuse to start: it would briefly show a "failed to initialize" window and then close/crash.
I deleted the whole fan control folder, and installed fresh, again 1.8.6.
Without the plugin, fan control starts normally.
When I install the plugin, the software fails again.
I added the content of the ADLX pluging folder one file at a time and the moment I add ` FanControl.ADLX.dll` the issue appears.

I think there was a recent AMD driver update that might have caused this.
I don't know where to find logs or the crash, but if you point me in the direction of the FanControl logs I can attach them here.

**Comment by Rem0o** [comment]
would be log.txt in the fancontrol folder.

**Comment by PaoloGB** [comment]
Thank you for your reply. I don't seem to have any log.txt file in the fan control folder.
![Screenshot 2024-04-02 193320](https://github.com/Rem0o/FanControl.ADLX/assets/27431089/9491b0ac-9a80-471d-aa91-c4212297b8c6)

**Comment by Rem0o** [comment]
Anything in EventViewer?

**Comment by RoaringYeti** [comment]
Have you found any fix to this problem? Have the exact same and I cant find any way to fix it. Have tried to get it to work for 2 hours now.

**Comment by RoaringYeti** [comment]
Same issue here. Had to uninstall the current adrenalin verion and install an older one for my software to work. Have sat with this for 3 hours now. Feel scared to install any new version of adrenalin any time soon since it probably will screw something up. 

Hope there will be any notice of when its safe to install a newer adrenalin version to not have to guess.

**Comment by PaoloGB** [comment]
```
Faulting application name: FanControl.exe, version: 186.0.0.0, time stamp: 0xb381c605
Faulting module name: ntdll.dll, version: 10.0.22621.3374, time stamp: 0xeae8eecc
Exception code: 0xc0000374
```

Event viewer shows the error above abode, consistent with the times I tried to load FanControl with the AMD driver installed.

**Comment by mrlinuxfish** [comment]
I too am noticing issues starting fancontrol with this plugin. I tried updating fancontrol, but that did not fix it

[log_old_install.txt](https://github.com/Rem0o/FanControl.ADLX/files/14895240/log.txt)
[log_fresh_install.txt](https://github.com/Rem0o/FanControl.ADLX/files/14895246/log.txt)

**Comment by RoaringYeti** [comment]
Seems to work now?

**Comment by PaoloGB** [comment]
@RoaringYeti Did you update the driver on adrenalin? Or windows update? Or directly from AMD?

**Comment by PaoloGB** [comment]
Closing this as the issue seems to be resolved by updating the AMD graphics drivers.
