### ISSUE TITLE
Refresh Sensors Detection (ctrl+R) crashes ALDX plugin, which crashes FanControl

### ISSUE THREAD

**Issue by SomeoneElse00** [Rem0o/FanControl.ADLX#34]
I've noticed that Fan Control has crashed whenever my computer goes into hibernate mode.

I further debuged this and tried a couple of menu items to retrigger this event and I found some error logs saying `ADLX plugin: ADLX Plugin: SupportsTargetFanSpeed returns false`. I found that these logs are created whenever the Refresh Sensors Detection (ctrl+R) menu option is executed manually or automatically.

FanControl launches without issue on startup, just has issues when refreshing after boot.  If I relaunch the program after the crash, it opens without any issue. I noticed after unblocking the dlls one by one that unblocking `ADLXCSharpBind.dll` changed the behavior. Now, whenever I refresh, it clears the config and the device list, but does not crash.

I have a Gigabyte 6600 XT, and am running windows 10. I appreciate the help!

**Comment by nikolarun** [comment]
I have the same issue with PC coming out of sleep. WIndows 10 22H2 7900XTX

**Comment by Rem0o** [comment]
@SomeoneElse00  Regarding the " ADLX plugin: ADLX Plugin: SupportsTargetFanSpeed returns false ", if you go into Adrenaline, are you able to set a manual fan speed on your card? Not the "advanced" with the graph, but straight % here:
![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/5c67c9aa-8fc6-46e4-8071-a5783cba0690)

Then if that works, if you leave it like this in adrenaline, "not advanced", and open Fancontrol, do you get the same "SupportsTargetFanSpeed returns false" ?

**Comment by SomeoneElse00** [comment]
I don't have adrenaline installed. Do I need to install it? I used to have my GPU's additional drivers installed, but replaced them with the barebones drivers from AMD (downloaded from gigabyte), and FanControl. I've had issues with drivers and unexpected behavior and I traced it back to the adrenaline client in the past.

**Comment by nikolarun** [comment]
@SomeoneElse00 @Rem0o I don't have the adrenaline installed either. I have msi afterburner runnning, if that helps with the testing

**Comment by Rem0o** [comment]
Give https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1 a try

**Comment by nikolarun** [comment]
The issue is fixed for me. thank you very much

**Comment by Rem0o** [comment]
> I spoke too soon. I left the PC on sleep overnight , and fancontrol crashed on wakeup

Yup, experienced it too.   There was an unreleased handle in the code when closing ADLX.   Fixed it. Try latest build out of https://ci.appveyor.com/project/Rem0o/fancontrol-adlx.

@nikolarun

**Comment by nikolarun** [comment]
Thanks, I have installed it and will report tomorrow

**Comment by nikolarun** [comment]
seems to be working fine. the only issue I had was Fancontrol crashing when I updated the driver via Device Manager, but I think that is expected.

**Comment by Rem0o** [comment]
Yeah driver updates are violent when you got handles opened. Glad it works ok for you otherwise.

**Comment by nikolarun** [comment]
thank you for the new version, installed already

**Comment by SomeoneElse00** [comment]
Issue hasn't popped back up in a while, I'm assuming the patch worked! Thanks @Rem0o, and thanks for help with troubleshooting @nikolarun
