### ISSUE TITLE
V0.1 No fan control and AMD Settings still overridden by percentages

### ISSUE THREAD

**Issue by mordang7** [Rem0o/FanControl.ADLX#37]
Thankful this is still being developed, tested the latest V0.1 version of the plugin with my 6800 XT but sadly it still does not work properly.

The RPM remains 0 with a a curve selected, with the forced option enabled and the manual override also does not work. 

Following this aforementioned issue, I check the AMD Tuning Settings (my custom profile specifically doesn't have ANY fan tuning enabled) but even if I reload my profile, FanControl will still override it and enable Fan Tuning and keep the RPM on 0 no matter the load and temperature (which can lead to issues if not damaged components). On top of that, this settings "override" that FanControl applies to the AMD settings for some reason changes ALL settings to percentages instead of the specific values that are manually selected by the user.

Just reporting my experience with the latest update.

Some - maybe - useful information:

FanControl versions used: 187 net8 (Standalone and Installed versions tested).

Last known working* ADLX Plugin version: 1.0.36 (?)
*buggy and CPU usage is very high

PC Information:

CPU: AMD Ryzen 5 5600X
RAM: 32GB @ 3600
GPU: MSI 6800 XT
OS NVMe: Samsung 980Pro 500GB
OS: Windows 11 23H2

Best workaround so far:

I have both curves created and applied a Mix curve with Max function, but use MSI afterburner to control the GPU fans and have copied the same fan curve there.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/02f685cc-d569-449f-a407-bceb62554fb5)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/c5673e99-f4de-47c8-8a36-7791825ced88)

Thank you Rem0o for the time and effort you keep putting into this project.

PS: Let me know if you need more info and if you want me to run any tests etc.

PS2: Edit reason: Reuploaded MSI Afterburner image as it wasn't posted the first time for some reason.

**Comment by kajoken** [comment]
Another owner of a 6800XT here and I can confirm this behavior. It's exactly the same for me.
"Zero RPM" Mode always gets activated when FanControl tries to take over the GPU controls.

**Comment by Rem0o** [comment]
> FanControl will still override it and enable Fan Tuning 

That's expected.  That's what the driver method does. 

> On top of that, this settings "override" that FanControl applies to the AMD settings for some reason changes ALL settings to percentages instead of the specific values that are manually selected by the user.

That's also expected.  FanControl doesn't create a graph in adrenaline, it applies a single value at a time, like it does for every other type of fans.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/7f3fee59-463c-4e5c-b52d-e73bb4715f51)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/d310bc49-dd3d-49ae-b3af-80337e430fed)

These two images show what's going on when FanControl sets a non-0 command, and then a zero command.

**Comment by mordang7** [comment]
> > FanControl will still override it and enable Fan Tuning
> 
> That's expected. That's what the driver method does.
> 
> > On top of that, this settings "override" that FanControl applies to the AMD settings for some reason changes ALL settings to percentages instead of the specific values that are manually selected by the user.
> 
> That's also expected. FanControl doesn't create a graph in adrenaline, it applies a single value at a time, like it does for every other type of fans.
> 
> ![image](https://private-user-images.githubusercontent.com/14118956/326264892-7f3fee59-463c-4e5c-b52d-e73bb4715f51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQ4OTgsIm5iZiI6MTcxNDMxNDU5OCwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjQ4OTItN2YzZmVlNTktNDYzYy00ZTVjLWI1MmQtZTczYmI0NzE1ZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0Mjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyM2M0ZjIyNjBiN2FjYTY0NTlmMDRhNWE4YzVjZDJmMGM1MmIyYTNmMzdlNWRlYzllYjdhYzExMzc1YTg5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OEmsDUmrPkXkLOEL8w8Uq3hts1lVOHAfcHKkKvlQFAo)
> 
> ![image](https://private-user-images.githubusercontent.com/14118956/326264919-d310bc49-dd3d-49ae-b3af-80337e430fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMTQ4OTgsIm5iZiI6MTcxNDMxNDU5OCwicGF0aCI6Ii8xNDExODk1Ni8zMjYyNjQ5MTktZDMxMGJjNDktZGQzZC00OWFlLWIzYWYtODAzMzdlNDMwZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE0Mjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MGE2ODFiODA4OTAyYTg3NjFlNDhhM2EyZGQxMjdjMTdiZTc3MzdiYWZkNTg3MmVkMGVkZjYzMDdkMDJjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5Y-bsx1m4EX5NuJPepCHYM1z7eYF8Qeb-x59Fxn_ZM)
> 
> These two images show what's going on when FanControl sets a non-0 command, and then a zero command.

Thank you for your reply.

I understand what you're trying to explain here, and maybe I didn't really get into more details regarding the issues.

In the case of enabling Zero RPM, MSI afterburner does what you're showing in your screenshots (enabling the Zero RPM when indicated by the percentage value of the curve and disabling it accordingly), but through FanControl the Zero RPM option stays enabled constantly which results in unwanted behavior (Fans are ALWAYS @ 0 RPM and never change value, even though the values change in FanControl "visually" only as a percentage).

The other issue I described rather poorly is that without FanControl with ADLX and MSI Afterburner managing the GPU fan curve the custom Tuning Profile I've created looks like this:

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/65661694-9a9c-440c-bd96-905e923ac1a2)

If I enable the ADLX Plugin (and completely exit out of MSI Afterburner), FanControl changes every single setting into percentages which is also unwanted behavior and leads to instabilities as percentages can - and will - translate into different values than the ones manually entered:

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/8ce72c38-3300-450e-91bb-c24a5ee447ec)

also manual control does not work at all as well as show in this screenshot:

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/64304ab4-4441-4357-8c60-49d9b3b19b19)

Thanks again for taking the time with this plugin.

**Comment by kajoken** [comment]
For me this does work if you're using manual control. The second you use an auto curve it's not working anymore.

![fancontrol](https://github.com/Rem0o/FanControl.ADLX/assets/72881333/0bb6ab20-7359-4c0f-a45d-ce00021ea7a0)

**Comment by Rem0o** [comment]
I may have found the issue with the ZeroRPM state. Try the latest build: https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

As for the Overclocking advanced control turning off, I have no clue why it does that.  It does it for me too.  It happens exactly when "SetFanTuningStates" is called in the driver.  Most likely a bug in ADLX.

**Comment by Rem0o** [comment]
Opened a bug here https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/16
Hope they respond.

**Comment by kajoken** [comment]
> I may have found the issue with the ZeroRPM state. Try the latest build: https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

This seemed to fix the issue partly. Starting FanControl will now detect the state correctly and don't set Zero RPM, but the second one tries to edit the curve it'll go back to Zero RPM and stay there. You don't even need to save the new curve. Just trying to edit is enough.

But it's already much better this way since I don't edit curves that much. Thank you for the fast response. :)

**Comment by Rem0o** [comment]
@kajoken The logic is this:

If 0% in fancontrol -> activate Zero RPM in adrenaline
if (> 0) % in fancontrol -> deactivate zero RPM in adrenaline

This is the % applied on the control card.  Also, deactivate the "GPU" section in sensor settings, only keep ADLX.

I tested it back and forth with a 7600x and is always does this, without issue.

**Comment by kajoken** [comment]
> @kajoken The logic is this:
> 
> If 0% in fancontrol -> activate Zero RPM in adrenaline if (> 0) % in fancontrol -> deactivate zero RPM in adrenaline
> 
> This is the % applied on the control card. Also, deactivate the "GPU" section in sensor settings, only keep ADLX.
> 
> I tested it back and forth with a 7600x and is always does this, without issue.

This did the trick. Disabling the GPU part threw some errors but after that it works perfectly fine. Thank you very much for your help in this. <3

**Comment by mordang7** [comment]
Good day, I tried the updated version with the suggested GPU section deactivated from the sensor settings of the app, and it is still not working properly for me.

Specifically manually controlling the GPU fan speed will work once, then after unticking the option, the GPU fans will go back to 0% and from that point on will stay there.

I also tried to do the automatic or manual pairing and every time ended up in 0% fan and no control whatsoever over it.

It now works sometimes - and not consistently - if I load FanControl with my settings and not touch anything except for editing my GPU fan curve in FanControl.

![image](https://github.com/Rem0o/FanControl.ADLX/assets/21289127/177e40a7-146d-4561-922d-2823a0e76587)

Thank you for your continued support and hard work, it is greatly appreciated!

**Comment by Rem0o** [comment]
@One thing to keep in mind: the 1-30% range or there about, depends on cards, is not available. It's either 0, or 30+.  Your graph should play arround that.

**Comment by mordang7** [comment]
> @one thing to keep in mind: the 1-30% range or there about, depends on cards, is not available. It's either 0, or 30+. Your graph should play arround that.

Thanks for pointing that out, I experimented with this in the past through MSI Afterburner and figured out the start % values for my card specifically.

Problem is that even under load the GPU fans remain at 0% (card goes over 79C core and 102C hotspot) and because of overheating the card underclocks, so I think that the curve percentage values are a non issue here.

Manual override also does nothing mind you.

BUT if I touch nothing after copying the ADLX files and enabling the Plugin (pairing etc.) it works OK-ish, and I say OK-ish because sometimes it just stays at 0 and never works again until I restart the FanControl app.

**Comment by kajoken** [comment]
> > @one thing to keep in mind: the 1-30% range or there about, depends on cards, is not available. It's either 0, or 30+. Your graph should play arround that.
> 
> Thanks for pointing that out, I experimented with this in the past through MSI Afterburner and figured out the start % values for my card specifically.
> 
> Problem is that even under load the GPU fans remain at 0% (card goes over 79C core and 102C hotspot) and because of overheating the card underclocks, so I think that the curve percentage values are a non issue here.
> 
> Manual override also does nothing mind you.
> 
> BUT if I touch nothing after copying the ADLX files and enabling the Plugin (pairing etc.) it works OK-ish, and I say OK-ish because sometimes it just stays at 0 and never works again until I restart the FanControl app.

Idk but your last screenshot shows that your GPU isn't matched with the speed sensor. I guess, it's something with that. 

Disabling the GPU sensor did throw errors for me so I uninstalled Fancontrol, deleted the config and reinstalled FanControl again, added the plugin before the very first start and disabled the GPU sensor in the very first assisted setup. After that, FanControl matched the sensors correctly and now everything works.

Since I had the same error with Zero RPM and could fix it that way, maybe this helps.

Mine looks like this atm.
![fancontrol](https://github.com/Rem0o/FanControl.ADLX/assets/72881333/7ebc5ae8-ab79-4aa2-8473-5d24388c2a14)

**Comment by biggestsonicfan** [comment]
> Also, deactivate the "GPU" section in sensor settings, only keep ADLX.

Worked for me with my RX 6750 TX!
