### ISSUE TITLE
"No speed sensor reacted to control sensor" for AMD RX 7800 XT

### ISSUE THREAD

**Issue by rhomble** [Rem0o/FanControl.ADLX#38]
During assisted setup Fan Control is saying "No speed sensor reacted to control sensor" for both the AMD RX 7800 XT and the integrated AMD Radeon Graphics. This results in the "GPU Fan" and "AMD Radeon Graphics" items within the Control section of the Fan COntrol Home page as grayed out. The ADLX plugins from this repo are showing in the Plugins section of settings.

**Comment by Rem0o** [comment]
If you put the RX 7800 in manual mode like so:
![image](https://github.com/Rem0o/FanControl.ADLX/assets/14118956/9b4f4165-045c-4ecf-8719-9e03d8fae775)

Do you get any fan speed change with the slider? (Go 100%)

**Comment by rhomble** [comment]
Still no fan speed:
![Screenshot 2024-04-28 153959](https://github.com/Rem0o/FanControl.ADLX/assets/12204891/3d2482fe-2084-4b70-a42a-b182372de298)

I also tried the "Force apply" toggle, but still no fan speed.

**Comment by rhomble** [comment]
UPDATE:

After turning off AMD Software's Zero RPM toggle under Performance > Tuning, the Control card and the associated Speed card did register the RPM value of the 7800 XT. It was prior to this of course it's just the RPM was actually 0.

However, I still cannot control the fan speed with Fan Control's Manual control:
![image](https://github.com/Rem0o/FanControl.ADLX/assets/12204891/e0afa96a-b1f7-4f1e-a9b7-e6a15bd1fdb7)

**Comment by Rem0o** [comment]
Disable the GPU section in sensor settings. Only keep ADLX on.

**Comment by rhomble** [comment]
That seems to be the fix! Thanks for the very quick help
