### ISSUE TITLE
Adrenalin Overrides Fan Control

### ISSUE THREAD

**Issue by BigFlubba** [Rem0o/FanControl.ADLX#39]
Ever since updating my GPU drivers yesterday, I have been fighting this issue where Adrenalin keeps taking control of the fans over time. If I disable custom fan control inside of Adrenalin and reload Fan Control it does work, but only for a few seconds, then Adrenalin takes over. I have Fan control on force apply and have updated the ADLX plugin to v1.0. So far nothing has fixed anything.

The curve Adrenalin defaults to.
![image](https://github.com/Rem0o/FanControl.ADLX/assets/69104450/c0028333-6327-452f-a3b5-5fda0b32fbf6)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/69104450/88be54ee-72c5-4201-aa25-826c2e9974fc)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/69104450/734ff81a-2a84-42c6-9eef-eee3f2b2247e)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/69104450/7cbea40b-5783-4e5d-ace3-5466e1991eb9)

![image](https://github.com/Rem0o/FanControl.ADLX/assets/69104450/e3133f3b-663c-4feb-bc22-a74efdc025e0)

**Comment by Rem0o** [comment]
First: Do not use Force apply. 
Second, Adrenaline is not taking over, it's just FanControl who ticks "Zero RPM", which resets the curve, that's normal. 
Now if your GPU is not stopping, that means it's too hot, so you should adjust your curve to zero RPM at a lower temperature.
Also, The 1%-30% range is usually not available, so do not try and run your gpu in that range in your fan curves.

**Comment by Rem0o** [comment]
It is what it is, you gotta play around the limitations.
