### ISSUE TITLE
V 1.0.27 Crashes Fan Control

### ISSUE THREAD

**Issue by LtLasagna** [Rem0o/FanControl.ADLX#4]
Not sure if I installed it correctly, I don't know how to compile it. I just grabbed the zip from AppVeyor.
I just unzipped it and put everything in the plugin folder.
[log.txt](https://github.com/Rem0o/FanControl.ADLX/files/10846410/log.txt)

**Comment by Rem0o** [comment]
> Result: ADLX_NOT_SUPPORTED
 
 All around. Seems like you ain't got the proper driver version/GPU.

**Comment by LtLasagna** [comment]
There is a different log I get as well, I'm going to reinstall everything just to make sure.
I have the right driver for a 5700xt

**Comment by Rem0o** [comment]
I don't think 5700xt supports ADLX.   So far I've only seen 7XXX series working.

**Comment by LtLasagna** [comment]
Ah, okay. Man that really sucks.
