### ISSUE TITLE
Fan spins at max when 0%

### ISSUE THREAD

**Issue by LennardPlay** [Rem0o/FanControl.ADLX#42]
With the latest update of FanControl my GPU is no longer supported, so I downloaded this Addon. Sadly the Fan spins up to 100% when it should be 0%. Is anyone able to reproduce this issue?

GPU: Radeon RX 580
Software: 
FanControl.ADLX ver. 1.0.67 from https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts
AMD Software: PRO Edition

Please let me know how I can send you more relevant information about the issue. Thank you very much for writing this addon :)

**Comment by Rem0o** [comment]
Show how you got it configured in FanControl ( screenshot ).

Also run this and show what's printed out in the console. 
[Test ADLX.zip](https://github.com/Rem0o/FanControl.ADLX/files/15351633/Test.ADLX.zip)

**Comment by LennardPlay** [comment]
![grafik](https://github.com/Rem0o/FanControl.ADLX/assets/60149904/76c6ac48-02e1-44cd-a482-779cb6b99ed6)
It seems to be happening after around 10 minutes or so.

The ADLXWrapper.exe runs through to 1000 and then closes automatically
![grafik](https://github.com/Rem0o/FanControl.ADLX/assets/60149904/d03af168-7979-4f01-b396-6003940453e6)

**Comment by LennardPlay** [comment]
Update: Now it seems to be happening every few minutes (around 5). The fan will speed up to what seems to be max speed for around 15 seconds and then returns to 0 RPM again

**Comment by Rem0o** [comment]
@LennardPlay  as far as Adrenaline is concerned, if you close FanControl, can you get your fan to behave using Adrenaline?

**Comment by LennardPlay** [comment]
I have to reset the fan profile to return to normal operation again.

When updating FanControl to V191 my GPU was detected again, so I don't need to rely on the ADLX plugin anymore. Thank you for updating :) Everything works fine again.

PS: I wanna donate 5€ to this great project. What's the best way to do this? (The one with the least percentage of fees)

**Comment by Rem0o** [comment]
Don't worry about the fees, just use whatever is convenient to you. Thanks for the support!
