### ISSUE TITLE
Not adjusting speed with a graph

### ISSUE THREAD

**Issue by Ambu13** [Rem0o/FanControl.ADLX#50]
So i updated  my windows 11pro tdy and my amd adrenaline to the new version. My gpu is a rx5700xt, note that before these updates it worked fine.
So tdy the fan control app didn't  even start. So i Uninstal it, after new clean instal i uploaded ny settings from the other install and put the plug in and i cant control gpu fam speed with a graph. If i use manual mode i can. But graph for some reason the pc uses the adrenaline one and not the fan control graph. This also happend the first time, but somehow i made it work. This time I can't.  Sry for bad inglês.  Stil learning. Thank u very mutch

**Comment by Ambu13** [comment]
Update. I tried everything until now even disabling the gpu sensor(which causes errors) tried unistaling and installing with the new plug-in for amd that u recommended in coment 40 I belive
 Nothing now it just doesn't control in any way. Before that the problem was it didn't follow the graph and it always started when in the gpu hotspot reached 80, but for test reasons I wnat it to star when the core it 80, which is normal in my gpu, u can argue is a safety measure by the gpu, still when the temps went down it would turn of the rpm. It just said everything below 50% it's the same as 50% rpm. And my gpu starts at 35%. So I calibrated that way, still nothing happend. It also says "this control doesnt respond properly to comand". Idk what's wrong cause before the app didn't oppend and I had yo reinstall everything was fine

**Comment by Rem0o** [comment]
How about you send a screenshot of your configuration.

**Comment by Ambu13** [comment]
sry i couldnt send cause it has a mb liit but here is a link so u can see everything
https://we.tl/t-2rB0p0XeCZ

**Comment by Ambu13** [comment]
![Captura de ecrã 2024-07-03 142516](https://github.com/Rem0o/FanControl.ADLX/assets/174552112/83973ed1-3df5-4bc8-93be-9590cbb07905)
here is only the screenshot

**Comment by Ambu13** [comment]
If u would like we can go on discord and u use TeamViewer  and see for ur self

**Comment by Rem0o** [comment]
Are you using the latest version of the plugin? https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.5
In your screenshot we can see that ZeroRPM is off, and it should be on with the plugin being sent a 0% command.

**Comment by Ambu13** [comment]
I will try it again and reinstall de plug in 
And the 0 rpm thing i tried it before  but i will do it again and report

**Comment by Ambu13** [comment]
Well i kind does work like it switched back to 0 when it reach 48 and not 55. And started in 55/60 idk if its a safety feature that overrides my settings
Anyway just to be sure the plugin i installed  is the first file of the link. Plus my amd version is 24.6.1
And i  did the windows update 3 days ago. The one that came in the most recently for Windows 11pro
Any tips? Or new suggestions?  Thanks for the hard work mate its very good

**Comment by Rem0o** [comment]
@Ambu13  you can't control the temperature at which your GPU will go 0 RPM. That's a "hard" setting set into the GPU, you can't change it. If it's 48, you got to play arround that temperature and set your graph to go 0 RPM  at or below 48 degree.

**Comment by Ambu13** [comment]
Oh ok, cause i had set to go to zero rpm at 55 degree and to star to spin at 56
In another graph to test as u can see in the video, i have set to star to spin at 80. But unfortunately it doesn't.  Thats why i asked if that is normal.
So it is normal and there is nothing i can do right?

**Comment by Rem0o** [comment]
Yes it's normal, You can't decide at which temperature the ZeroRPM "trigger" point is.

**Comment by Ambu13** [comment]
Ok then thank u very mutch. U helped a lot
