### ISSUE TITLE
Did I do this right?

### ISSUE THREAD

**Issue by test3211234** [Rem0o/FanControl.ADLX#52]
So I installed the plugin and went back to the main screen. Now instead of my regular "CPU", "Case Fans", and "GPU", there was also "AMD Radeon RX 6600". But there can't be two GPUs. So I did the assisted setup again and now there was only the original three that I mentioned before. The "AMD Radeon RX 6600" one was gone. So now I set my GPU fan curve source to the one that ends with "- ADLX". Did I do this right?

**Comment by test3211234** [comment]
Nope, something's still up when I start a game and there's a question mark.

**Comment by Rem0o** [comment]
FanControl now has built-in ADLX support, the plugin is basically baked in.  You can remove the plugin all together and use the sensors displayed by the software alone.
