### ISSUE TITLE
Adrenaline tuning settings

### ISSUE THREAD

**Issue by perroboc** [Rem0o/FanControl.ADLX#6]
First of all, so far, it works! So thank you!

But as with every development, some funny things happen:

Fan #0 reports the same fan speed as the newly created fan #8. But Fan #0 is not able to control the speed, only the new one does.
![image](https://user-images.githubusercontent.com/2722773/226148143-935a25b9-af66-4e05-a513-2f5696f2417a.png)

0 RPM setting seems to not be working correctly
![image](https://user-images.githubusercontent.com/2722773/226148207-aec79682-954c-4944-95e8-0fff0758aeba.png)

And last but not least, fancontrol seems to change the advanced control settings off for GPU and VRAM tuning options
![ezgif-2-e8e35a7d2d](https://user-images.githubusercontent.com/2722773/226148536-0933ff96-d17e-47d1-86a6-7ce25f37d569.gif)

These are just details, though! thank you!!

**Comment by Rem0o** [comment]
Because than Fan0 must be coming from LibreHardwareMonitor, while the new one is from the plugin.

As for the tuning options, I'm not sure why they get reset.

**Comment by panda4k** [comment]
I can confirm that FanControl with this plugin changes all the settings, including tuning settings, in Adrenalin. Not sure it applies them tho. RX 6900 XT here.

**Comment by MacIntoc** [comment]
No issue with the 0RPM for me but i can also confirm that the advanced control switches are automatically disabled by the plugin for GPU and VRAM settings. This is particularly annoying when setting the GPU voltage because every mV counts (at least for 7x00 series) and AMD hasn't bothered to add decimal percentages (so 1% corresponds to 11mV~12mV).

**Comment by astorm67** [comment]
6700 XT, also noticing the plugin disables advanced control switches. Otherwise, it's been a great plugin for me so far!

**Comment by catsz** [comment]
The zero RPM works for me but setting the graph anywhere below 15% on the fans doesn't work. I also do not believe that if the GPU is over 50c that zero rpm works

**Comment by Rem0o** [comment]
Good news:
https://github.com/Rem0o/FanControl.ADLX/discussions/36

0 RPM mode should work properly now.
