### ISSUE TITLE
Can I download it if it's not compiled? If I compile it myself, do I need to prepare other software?

### ISSUE THREAD

**Issue by bluehysteric** [Rem0o/FanControl.ADLX#8]
Can I download it if it's not compiled? If I compile it myself, do I need to prepare ADLX sdk?

**Comment by Rem0o** [comment]
The required dlls are in the DLL folder.

**Comment by bluehysteric** [comment]
> 

I tried to drag all the files inside the dll folder into the Plugins folder, but nothing happens. I tried to change the names of the ADLXWrapper & ADLXCSharpBind files but nothing happens either. How does it work exactly, please?

**Comment by bluehysteric** [comment]
> Oh, I thought you wanted to compile the source yourself. My bad.

I'm not very good at compiling my own, and I'm asking if there are any already compiled?

**Comment by Rem0o** [comment]
https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

**Comment by bluehysteric** [comment]
> https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

Thank you very much

**Comment by bluehysteric** [comment]
> https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

ADLX.dll after I installed FanControl.ADLX.dll, re-detected the sensor, and then it was in REFRESHING all the time

**Comment by bluehysteric** [comment]
> ADLX.dll after I installed FanControl.ADLX.dll, re-detected the sensor, and then it was in REFRESHING all the time
> Finally it shows installation failure

ADLX.dll after I installed FanControl.ADLX.dll, re-detected the sensor, and then it was in REFRESHING all the time
Finally it shows installation failure

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
