### ISSUE TITLE
Excessive CPU usage (~3.3%)

### ISSUE THREAD

**Issue by kotauskas** [Rem0o/FanControl.ADLX#9]
*(Transcluded from [the issue I erroneously opened on the mainline FanControl repo][iss])*

**Describe the bug**
With the ADLX plugin and a fairly regular fan curve, FanControl perpetually sits at roughly 3.3% of CPU usage (with 12 logical processors in the system). A quick peek into Process Hacker reveals that 2 threads are responsible for most of that usage, the TIDs of which change all the time. Frequent termination and spawning of threads can also be seen.

![Process Hacker thread list](https://user-images.githubusercontent.com/28248600/236703192-1cf36da5-5acd-4105-a556-6f35d58af295.png)

Additionally, as per Process Hacker's statistics, roughly ⅔ of all the CPU time of the process is being spent in kernel mode.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope.

**Relevant hardware specs and setup**
- CPU: AMD Ryzen 5 3600
- GPU (only device whose fan is being controlled): AMD Radeon RX 6600

[iss]: https://github.com/Rem0o/FanControl.Releases/issues/1763

**Comment by kotauskas** [comment]
@mordang7, just as a heads up, MSI Afterburner is a decent temporary alternative for controlling the temperature at which Zero RPM is engaged. The following setup works quite well for me, at a much smaller CPU cost than FanControl.ADLX:
![image](https://github.com/Rem0o/FanControl.ADLX/assets/28248600/3e3231db-627d-4968-8329-b72ca865c0da)

**Comment by mordang7** [comment]
@Rem0o Thank you for your reply and explanation, I really appreciate it! I am no expert, not by a mile actually. If you want me to test any betas, or need more information let me know and I'll help as much as I can.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
